contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
        path('', views.index, name='index'),  # 一覧画面
        path('contact_form/', views.contact_form, name='contact_form'),  # フォーム
        path('contact_form/contact/complete/', views.complete, name='complete'),  # 完了画面
]

contactform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')), 
]

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(label='件名', max_length=100)
    sender = forms.EmailField(label='Email', help_text='※ご確認の上、正しく入力してください。')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    myself = forms.BooleanField(label='同じ内容を受け取る', required=False)

contact/views.py
# project/contact/views.py

from django.shortcuts import render,redirect
from .forms import ContactForm

from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail

""" 一覧画面"""
def index(request):
    return render(request, 'contact/index.html')


def contact_form(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            """ 追記"""
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = "送信元:{}\n内容:{}".format(sender,form.cleaned_data['message'])
            myself = form.cleaned_data['myself']
            recipients = [settings.EMAIL_HOST_USER]

            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
              
            if myself:
                try:
                  message = """
お問合せいただきありがとうございます。
数日以内にこちらからご連絡させていただきます。
ご不明な点等ございましたら、気軽にご連絡ください。
-------------------------------------------------
{}
{}
                  """.format(settings.USER_NAME,settings.EMAIL_HOST_USER)
                  send_mail(subject, message, sender, [sender])
                except BadHeaderError:
                  return HttpResponse('無効なヘッダーが見つかりました。')
            return redirect('contact:complete')

    else:
        form = ContactForm()

    return render(request, 'contact/contact_form.html', {'form': form})

# """ お問い合わせフォーム画面"""
# def contact_form(request):
#     return render(request, 'contact/contact_form.html')


""" 送信完了画面"""
def complete(request):
    return render(request, 'contact/complete.html')

contact/templates/contact/complete.html
<center>
  <h1>送信完了</h1>
  <a href="{% url 'contact:index' %}">
      <p>トップへ</p>
  </a>
</center>

contact/templates/contact/contact_form.html
<style>

  .field  {
      margin-top: 20px;
  }

  label {
      display: block;
  }

  input {
      width: 20%;
      padding: 5px;
      box-sizing: border-box;
      border: solid 2px;
  }

  .help {
      color: red;
  }

  textarea {
      width: 50%;
      box-sizing: border-box;
      border-radius: 4px;
      border: solid 2px;
  }

  button {
      margin-top: 30px;
      width: 10%;
      padding: 5px;
  }

</style>
<center>
  <h1>入力フォーム</h1><hr>
  <br>

  <form action="{% url 'contact:contact_form' %}" method="post">
      {% csrf_token %}
      {% for field in form %}
          <div class="field">
              {{ field.errors }}
              {{ field.label_tag }}
              {{ field }}
              {% if field.help_text %}
                  <p class="help">{{ field.help_text|safe }}</p>
              {% endif %}
          </div>
      {% endfor %}
      <button type="submit">送信</button>
  </form>
</center>

contact/templates/contact/index.html
<!doctype html>
<html>
    <head>

        <title>Webサイト</title>

    </head>
    <body>

        <center>
            <a href="{% url 'contact:contact_form' %}">
                <h2>お問い合わせフォーム</h2>
            </a>
        </center>

    </body>
</html>